stages:
  prepare:
    cmd: python -m src.prepare
    deps:
      - src/prepare.py
      - src/common.py
      - data/raw/WineQT.csv
    params:
      - seed
      - split
    outs:
      - data/processed/train.csv
      - data/processed/test.csv
  train:
    cmd: python -m src.train
    deps:
      - src/train.py
      - src/common.py
      - data/processed/train.csv
    params:
      - seed
      - train
    outs:
      - models/model.joblib
  evaluate:
    cmd: python -m src.evaluate
    deps:
      - src/evaluate.py
      - src/common.py
      - models/model.joblib
      - data/processed/test.csv
    metrics:
      - metrics.json:
          cache: false
